Style/HashSyntax:
  EnforcedStyle: hash_rockets

Lint/UnusedBlockArgument:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    reduce: 'inject'

Style/EmptyLinesAroundBody:
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: true

Style/SignalException:
  Enabled: true
  EnforcedStyle: only_raise

Style/SingleSpaceBeforeFirstArg:
  Enabled: true

Style/SpaceInsideHashLiteralBraces:
  Enabled: true

Style/SpecialGlobalVars:
  Enabled: true

inherit_from: .rubocop_todo.yml
