AllCops:
  Exclude:
    - 'gems/**/*'

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Lint/AmbiguousOperator:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: true

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    reduce: 'inject'

Style/EachWithObject:
  Enabled: false

Style/EmptyLinesAroundBody:
  Enabled: true

Style/FileName:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: true

Style/RegexpLiteral:
  MaxSlashes: 0

Style/SignalException:
  Enabled: true
  EnforcedStyle: only_raise

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: true

Style/SpaceInsideHashLiteralBraces:
  Enabled: true

Style/SpecialGlobalVars:
  Enabled: true

Style/StringLiterals:
  Enabled: true

Style/TrailingComma:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: true

inherit_from: .rubocop_todo.yml
